Repository solun-pm/solun-api, pull requests merged in 2023-06, with the labels that each got.

#1 Added Solun PM api routes
  .env.local
  .gitignore
  package-lock.json
  package.json
  src/functions/file/check.ts
  src/functions/file/receive.ts
  src/functions/message/check.ts
  src/functions/message/create.ts
  src/functions/message/delete.ts
  src/functions/message/receive.ts
  src/server.ts
  tsconfig.json
Labels: enhancement

#3 Added all api routes from solun auth and from solun pm some download and delete and upload
  .env.local
  package-lock.json
  package.json
  src/functions/database/save_temp_token.ts
  src/functions/file/check.ts
  src/functions/file/delete.ts
  src/functions/file/download.ts
  src/functions/file/receive.ts
  src/functions/file/upload.ts
  src/functions/message/check.ts
  src/functions/message/create.ts
  src/functions/message/delete.ts
  src/functions/message/receive.ts
  src/functions/two_factor/disable.ts
  src/functions/two_factor/enable.ts
  src/functions/two_factor/verify.ts
  src/functions/user/beta_features.ts
  src/functions/user/change_pwd.ts
  src/functions/user/check.ts
  src/functions/user/create.ts
  src/functions/user/fast_login.ts
  src/functions/user/jwt_details.ts
  src/functions/user/login.ts
  src/functions/user/user_details.ts
  src/functions/user/validate_pwd.ts
  src/mail/mail.ts
  src/server.ts
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#4 Updated packages
  package-lock.json
  package.json
Labels: enhancement

#5 Fixed routes ig and added cors
  package-lock.json
  package.json
  src/functions/database/save_temp_token.ts
  src/functions/two_factor/disable.ts
  src/functions/two_factor/enable.ts
  src/functions/two_factor/verify.ts
  src/functions/user/beta_features.ts
  src/functions/user/change_pwd.ts
  src/functions/user/check.ts
  src/server.ts
Labels: enhancement

#6 Docker
  .dockerignore
  .github/workflows/docker-image.yml
  Dockerfile
  docker-compose.yml
Labels: enhancement

#9 Quick-Fix-2
  src/server.ts
Labels: enhancement

#10 Bug fixes
  .env.local
  src/functions/user/change_pwd.ts
  src/functions/user/check.ts
  src/functions/user/create.ts
  src/functions/user/login.ts
  src/server.ts
Labels: enhancement

#11 Bug fix
  src/functions/two_factor/enable.ts
  src/functions/two_factor/verify.ts
Labels: enhancement

#12 added mail aliases api endpoint
  src/mail/mail.ts
Labels: enhancement

#13 Added Webmail api routes
  src/functions/webmail/jwt_details.ts
  src/functions/webmail/login.ts
  src/functions/webmail/pre_auth.ts
  src/functions/webmail/user_details.ts
  src/server.ts
Labels: enhancement

#14 Bug fixes and added stats api route
  src/functions/stats/api_log.ts
  src/functions/two_factor/verify.ts
  src/functions/user/login.ts
  src/generate/generate.ts
  src/server.ts
Labels: bug, enhancement

#15 More bug fixes (app, app password)
  src/functions/webmail/login.ts
  src/server.ts
Labels: enhancement

#16 Update docker-image.yml
  .github/workflows/docker-image.yml
Labels: enhancement

#18 file / msg route adjustments
  .env.local
  .github/workflows/docker-image.yml
  Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/functions/file/check.ts
  src/functions/file/upload.ts
  src/functions/message/create.ts
  src/functions/message/receive.ts
  src/functions/user/create.ts
Labels: bug, enhancement

#19 Added ACL update
  package-lock.json
  package.json
  src/functions/user/create.ts
  src/mail/mail.ts
Labels: enhancement

#20 Added Timeout, Added Alias routes for dashboard
  package-lock.json
  package.json
  src/functions/user/alias/add_alias.ts
  src/functions/user/alias/delete_alias.ts
  src/functions/user/alias/get_alias.ts
  src/functions/user/get_domains.ts
  src/functions/user/login.ts
  src/mail/mail.ts
  src/server.ts
Labels: bug, enhancement
